### ISSUE TITLE
Consolidate naming

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/mtg#17]
What naming conversions will we follow for modules, UI components etc?
Is there a way to enforce casing etc on file names?

Once these question has been answered, make sure that everything within the repo follows the conventions

**Comment by Korla** [comment]
I see three conventions which need addressing:
- camelCase for normal js-files
- kebab-case for normal js-files
- PascalCase for React components

We need to decide two things to resolve this:
1. Should we use camelCase of kebab-case
2. Should we use PascalCase for React components or not

**Comment by Korla** [comment]
I vote for camelCase all over since I find that easier than kebab-case. React components do not need special treatment, they are functions like any other when I am coding, IMO. Folder structure will help to make things clear, I think.

But I am happy with any convention.

**Comment by pardahlman** [comment]
This looks interesting, no? https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md

**Comment by Korla** [comment]
Looks great!
