### ISSUE TITLE
Mana pool

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/mtg#8]
A pre-req for #7 is to be able to tap lands for mana 😛

**Comment by Korla** [comment]
Tapping a land for mana is a perfect candidate for the first [activated ability](https://mtg.gamepedia.com/Activated_ability). And I think that can be developed before even playing spells.

Thinking some more about it, I realise that tapping the land for mana is the cost, i.e. for a forest:

`Tap ~: Add G to your mana pool`

Where `~` refers to [THIS]-card.

**Comment by Korla** [comment]
This has now been implemented by #30
